name: Browser Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  dusk-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql, bcmath, dom, fileinfo, ctype, json, tokenizer, xml, gd, zip
          coverage: none
          tools: composer:v2
          
      - name: Verify PHP version
        run: php -v

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 libx11-xcb1
          composer install --prefer-dist --no-progress --no-suggest
          cp .env.example .env
          php artisan key:generate
          
          # Configure .env for Dusk
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env
          
          php artisan dusk:chrome-driver
          
      - name: Run Dusk Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          php artisan migrate:fresh --seed
          php artisan serve --no-reload > /dev/null 2>&1 &
          php artisan dusk --colors=never

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tests/Browser/screenshots
          if-no-files-found: ignore

      - name: Upload Console Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: console-logs
          path: tests/Browser/console
          if-no-files-found: ignore
