name: Deploy MyUKM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: |
          ~/.composer/cache
          node_modules
        key: ${{ runner.os }}-deps-${{ hashFiles('composer.lock') }}-${{ hashFiles('package-lock.json') }}
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, ctype, fileinfo, openssl, PDO, tokenizer, xml, gd, pdo_mysql
    - run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
        npm ci && npm run prod
    - run: |
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --seed
        php artisan test
    - run: composer audit --no-interaction
    - uses: rtCamp/action-slack-notify@v2
      if: always()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Deploy MyUKM ${{ job.status }} 🚀"
    - run: echo "🚀 Deploying to production..."
      if: github.ref == 'refs/heads/main'
