name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: myukm_test
          MYSQL_USER: root
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, pdo_mysql, bcmath, gd, intl, json, xml, ctype, fileinfo, tokenizer, xmlwriter, iconv, exif, gmp, imagick
        coverage: none
        tools: composer:v2

    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        cp .env.example .env
        php artisan key:generate
        
    - name: Configure Environment for Testing
      run: |
        echo "APP_ENV=testing" > .env.testing
        echo "DB_CONNECTION=mysql" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=myukm_test" >> .env.testing
        echo "DB_USERNAME=root" >> .env.testing
        echo "DB_PASSWORD=secret" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing
        cp .env.testing .env
        
    - name: Clear migration cache
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan optimize:clear
        
    - name: Reset Database
      run: |
        # Clear all caches first
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan optimize:clear
        
        # Drop all tables
        php artisan db:wipe --force
        
        # Run basic migrations first
        php artisan migrate:refresh --path=database/migrations/001_create_users_table.php
        php artisan migrate:refresh --path=database/migrations/002_create_chats_table.php
        php artisan migrate:refresh --path=database/migrations/003_create_sessions_table.php
        php artisan migrate:refresh --path=database/migrations/004_create_groups_table.php
        php artisan migrate:refresh --path=database/migrations/005_create_group_user_table.php
        php artisan migrate:refresh --path=database/migrations/006_create_cache_table.php
        
        # Run our final fix migration
        php artisan migrate:refresh --path=database/migrations/2025_06_28_155300_final_fix.php
        
        # Mark all other migrations as done
        php artisan migrate:install
        php artisan migrate:status | grep -v '^\s*[0-9]\{4\}_' | grep -v '^\s*$' | awk '{print $2}' | xargs -I {} php artisan migrate:mark-done {}
        
        # Clear all caches
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
      
    - name: Execute tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: myukm_test
        DB_USERNAME: root
        DB_PASSWORD: secret
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        TEST_DATABASE: myukm_test
      run: |
        php artisan test
