name: Run Laravel Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: myukm_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql, bcmath, dom, fileinfo, ctype, json, tokenizer, xml, gd, zip
          coverage: none
          tools: composer:v2
          
      - name: Verify PHP version
        run: php -v

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate App Key
        run: |
          php -r "
          file_put_contents(
              '.env',
              str_replace(
                  'APP_KEY=',
                  'APP_KEY=base64:' . base64_encode(random_bytes(32)),
                  file_get_contents('.env')
              )
          );
          "

      - name: Configure Environment
        run: |
          # Database Configuration
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=myukm_test/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env
          
          # Testing Environment
          echo "APP_ENV=testing" >> .env
          
          # Cache and Session Configuration
          echo "CACHE_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "SESSION_LIFETIME=120" >> .env
          
          # Broadcasting Configuration
          echo "BROADCAST_DRIVER=none" >> .env
          
          # Dummy Pusher Credentials (to prevent null errors)
          echo "PUSHER_APP_ID=test" >> .env
          echo "PUSHER_APP_KEY=test" >> .env
          echo "PUSHER_APP_SECRET=test" >> .env
          echo "PUSHER_APP_CLUSTER=mt1" >> .env
          echo "PUSHER_HOST=" >> .env
          echo "PUSHER_PORT=443" >> .env
          echo "PUSHER_SCHEME=https" >> .env
          echo "PUSHER_APP_CLUSTER=" >> .env
          
          # Disable Pusher service provider for tests
          sed -i "s/App\\Providers\\BroadcastServiceProvider::class,//g" config/app.php
          
      - name: Install Composer Dependencies
        env:
          BROADCAST_DRIVER: 'none'
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
          PUSHER_APP_ID: test
          PUSHER_APP_KEY: test
          PUSHER_APP_SECRET: test
          PUSHER_APP_CLUSTER: mt1
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test
