name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    # Remove MySQL service, not needed for SQLite

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, xml, mysql, pdo_mysql, sqlite3
        coverage: none

    - name: Copy .env
      run: |
        cp .env.example .env.testing
        echo "APP_ENV=testing" >> .env.testing
        echo "APP_DEBUG=true" >> .env.testing
        echo "DB_CONNECTION=sqlite" >> .env.testing
        echo "DB_DATABASE=:memory:" >> .env.testing
        echo "DB_FOREIGN_KEYS=true" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        cat .env.testing

    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        cp .env.testing .env

    - name: Generate key
      run: php artisan key:generate --env=testing

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run Migrations (SQLite)
      run: |
        php artisan migrate:fresh --env=testing --force

    - name: Run Tests
      run: |
        php artisan config:clear
        php artisan test --env=testing

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          storage/logs/laravel.log
          storage/logs/test-results.xml
