name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, sqlite, fileinfo, ctype, json, tokenizer, xml, gd, zip, intl
        coverage: none
        tools: composer:v2

    - uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Configure Environment for Testing
      run: |
        echo "APP_ENV=testing" > .env.testing
        echo "DB_CONNECTION=sqlite" >> .env.testing
        echo "DB_DATABASE="$(pwd)"/database/database.sqlite" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing
        cp .env.testing .env
        
    - name: Clear migration cache
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan optimize:clear
        
    - name: Reset Database
      run: |
        # Clear all caches first
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan optimize:clear
        
        # Drop all tables and re-run all migrations
        php artisan db:wipe --force
        
        # Run all migrations in a single command to ensure proper order
        php artisan migrate:fresh --force
        
        # Clear all caches
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
      
    - name: Execute tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
